# Generated by Django 3.2.14 on 2022-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('avatar', models.ImageField(upload_to='avtor/')),
                ('bio', models.TextField()),
                ('work_place', models.CharField(max_length=128, null=True)),
                ('instagram_link', models.CharField(max_length=128)),
                ('facebook_link', models.CharField(max_length=128)),
                ('twitter_link', models.CharField(max_length=128)),
                ('pinterest_link', models.CharField(max_length=128)),
                ('posts_count', models.IntegerField(default=0)),
                ('is_top', models.BooleanField(default=False)),
                ('jobs', models.ManyToManyField(to='author.AuthorJob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
